### Data Science Notes 9/17/20
### *NumPy*
### George P. Tryfiates

In [1]:
import numpy as np

### Array Creation

In [4]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
a = np.array([2, 3, 4])
a
a.dtype

dtype('int32')

In [25]:
b = np.array([(1,2), (4,5,6)])
b

array([(1, 2), (4, 5, 6)], dtype=object)

In [26]:
c = np.array([[1,2], [3,4]], dtype = complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### Default dtypes

In [28]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((2,3,4), dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [34]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

#### Create a Sequence of #'s

In [39]:
np.arange(5)


array([0, 1, 2, 3, 4])

In [38]:
np.arange(0,2,1)

array([0, 1])

In [40]:
np.arange(10,30,5)

array([10, 15, 20, 25])

Better Way: Define how many #'s you want (Esp. Better working w/floating point)

In [41]:
np.linspace(0,1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [43]:
np.linspace(0,3,3)

array([0. , 1.5, 3. ])

In [44]:
np.linspace(0,2,3)

array([0., 1., 2.])

### Printing

Top to bottom. If it's too large it skips the center of the array with "..."